### ISSUE TITLE
Some boundaries of villages are weird

### ISSUE THREAD

**Issue by maelle** [gggodhwani/telangana_boundaries#3]
Thanks again for scraping these data! :grinning: ! I was so excited to get these boundaries!

I have used Leaflet in R for visualizing the data, with the code

``` r
library("leaflet")
library("rgdal")

output1 <- readOGR("telangana_boundaries-master/districts.json",
                   layer = "OGRGeoJSON")
output1 <- subset(output1, D_N == "RANGAREDDY")

output2 <- readOGR("telangana_boundaries-master/blocks.json",
                   layer = "OGRGeoJSON")
output2 <- subset(output2, D_N == "RANGAREDDY")

output3 <- readOGR("telangana_boundaries-master/village_boundaries.json",
                   layer = "OGRGeoJSON")
output3 <- subset(output3, D_N == "RANGAREDDY")

m <- leaflet() %>% setView(lng =  78.55714, lat = 17.12903, zoom = 7) %>%
  addTiles() %>%
  addPolygons(data = output3,
              color = "blue",
              fillColor = "blue",
              fill = TRUE,
              fillOpacity = 0.4,
              popup = output3@data$DMV_N)

library(htmlwidgets)
saveWidget(m, file="m4.html")
```

In some cases, villages are circles. In the example below one sees that the boundaries for Ibrahimpatnam moreover do not correspond to the satellite (?) data from Openstreetmap.

![strange_limits](https://cloud.githubusercontent.com/assets/8360597/14741281/71de2172-0895-11e6-8562-f48fa3736b30.png)

I know it's not your fault and I'm very grateful for the data. I just wonder whether you know if it often happens that village boundaries are unreliable?

I attach the widget map as zip 

[m4.zip](https://github.com/gggodhwani/telangana_boundaries/files/231756/m4.zip)

**Comment by gggodhwani** [comment]
@masalmon I see the same issue (zoomed to that village in QGIS)
![telangana](https://cloud.githubusercontent.com/assets/2306011/14769892/b3da0eb4-0a80-11e6-867d-ac06abcb045c.jpg)

And so we see on the official website:
![telangana_mis](https://cloud.githubusercontent.com/assets/2306011/14770143/b750c27a-0a87-11e6-8bc2-af9a1b09e3b2.png)

Unfortunately [Telangana State Remote Sensing Application Centre](http://tracgis.telangana.gov.in/TIS/TISNEW/tsiic/Default.aspx) doesn't talk about how they collected these administrative boundaries. Thus, I am assuming these were collected from 2011 Census(there could be a possibility that these boundaries date much before) and haven't got updated yet.

**Comment by maelle** [comment]
Thanks a lot! The circles look as if for some villages the boundaries are a centroid+guesstimate of a diameter 😉

It's great if the boundaries are from 2011... for being able to use the village wise census data there are on data.gov.in! ☺
